# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20171203_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Bost',
        ),
    ]
